### ISSUE TITLE
关于 C4 模型编写的讨论

### ISSUE THREAD

**Issue by NekoSilverFox** [NekoSilverFox/EasyQQ#14]
流程需要参考：

[用于软件架构的 C4 模型](https://www.infoq.cn/article/C4-architecture-model/)

**Comment by NekoSilverFox** [comment]
请将与会时间写至此地
2021/12/3~2021/12/6 之间

**Comment by liyijiadou2020** [comment]
收到，12月4日下午4点开会。

**Comment by NekoSilverFox** [comment]
ok
